- 👋 Hi, I’m @AydinAmanzholov
- 👀 I’m interested in KZAirForce...
- 🌱 I’m currently learning Eglish to exchang experience...
- 💞️ I’m looking to collaborate on foreignerry company ...
- 📫 How to reach me you can found me at yhe home ...

<!---
AydinAmanzholov/AydinAmanzholov is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
